name: "Dispatch Event to Build CI"
on:
  push:
    branches: 
      - main
    tags:
      - "*.*.*"
jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-step.outputs.tag }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Extract tag
      id: tag-step
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
  send-update-to-build-ci:
    name: Send Update to Build CI repo
    runs-on: ubuntu-latest
    needs: extract-tag
    steps:
      - name: Send event to build-ci repo
        run: |
          curl -XPOST -u "${{ secrets.RELEASE_BUILD_CI_PAT_USERNAME }}:${{ secrets.RELEASE_BUILD_CI_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/ACCESS-NRI/build-ci/actions/workflows/build-and-push-image-base-spack.yml/dispatches --data '{"ref": "main", "inputs":{"spack-packages-version": "${{ needs.extract-tag.outputs.tag }}"}}'
        

