name: "Dispatch Event to Build CI"
on:
  push:
    branches:
      - main
    tags: 
      - '*.*.*'

jobs:
  send-update-to-build-ci:
    name: Send Update to Build CI repo
    runs-on: ubuntu-latest
    steps:
      - name: Send event and tag to build-ci repo
        run: |
          curl -XPOST -u "${{ secrets.RELEASE_BUILD_CI_PAT_USERNAME }}:${{ secrets.RELEASE_BUILD_CI_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/ACCESS-NRI/build-ci/actions/workflows/notified-of-spack-packages-update.yml/dispatches --data '{"ref": "main", "inputs":{"spack-packages-version": "${{ github.ref_name }}"}}'
