name: "Dispatch Event to Build CI"
on:
  push:
    branches:
      - main
    tags: 
      - '*.*.*'
    paths:
      - '**.py'

jobs:
  send-update-to-build-ci:
    name: Send Update to Build CI repo
    runs-on: ubuntu-latest
    steps:
      - name: Get names of directories modified in push
        id: directories
        run: |
          # get all the changed files in the push, only keep the parent directory (corresponds to the package name), and turn it into a space-separated list!
          echo "modified=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }} | cut -d '/' -f 2 | tr '\n' ' ')" >> $GITHUB_OUTPUT
          
      - name: Send event and tag to build-ci repo
        run: |
          curl -XPOST -u "${{ secrets.RELEASE_BUILD_CI_PAT_USERNAME }}:${{ secrets.RELEASE_BUILD_CI_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" https://api.github.com/repos/ACCESS-NRI/build-ci/actions/workflows/notified-of-spack-packages-update.yml/dispatches \
            --data '{"ref": "main", "inputs":{"spack-packages-version": "${{ github.ref_name }}", "packages": "${{ steps.directories.outputs.modified }}"}}'
