name: "Dispatch Event to Build CI"
on:
  push:
    branches: [main]
jobs:
  send-update-to-build-ci:
    name: Send Update to Build CI repo
    runs-on: ubuntu-latest
    steps:
      - name: Send event to build-ci repo
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/ACCESS-NRI/build-ci/actions/workflows/build-and-publish-base-spack.yml/dispatches --data '{"ref": "main"}'
        

