name: Python Checks
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - main
    paths:
      - '**.py'
jobs:  
  ruff-check:
    name: Check syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get py files changed
        id: get-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**.py'
      - if: ${{ fromJson(steps.get-files.outputs.all_changed_files_count) > 0 }}
        uses: chartboost/ruff-action@v1
        with:
          src: "${{ steps.get-files.outputs.all_changed_files }}"
          version: 0.1.1
          args: "check --preview --config .ruff.toml"
